//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mybrary.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mybrary.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BusyLabel {
            get {
                return ResourceManager.GetString("BusyLabel", resourceCulture);
            }
        }
        
        internal static string ScanBook {
            get {
                return ResourceManager.GetString("ScanBook", resourceCulture);
            }
        }
        
        internal static string BookList {
            get {
                return ResourceManager.GetString("BookList", resourceCulture);
            }
        }
        
        internal static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        internal static string BookOwned {
            get {
                return ResourceManager.GetString("BookOwned", resourceCulture);
            }
        }
        
        internal static string AlternativeISBNOwned {
            get {
                return ResourceManager.GetString("AlternativeISBNOwned", resourceCulture);
            }
        }
        
        internal static string ToggleTorch {
            get {
                return ResourceManager.GetString("ToggleTorch", resourceCulture);
            }
        }
        
        internal static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        internal static string Owned {
            get {
                return ResourceManager.GetString("Owned", resourceCulture);
            }
        }
        
        internal static string Want {
            get {
                return ResourceManager.GetString("Want", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ErrorInternetTitle {
            get {
                return ResourceManager.GetString("ErrorInternetTitle", resourceCulture);
            }
        }
        
        internal static string ErrorInternetMessage {
            get {
                return ResourceManager.GetString("ErrorInternetMessage", resourceCulture);
            }
        }
        
        internal static string BasicError {
            get {
                return ResourceManager.GetString("BasicError", resourceCulture);
            }
        }
        
        internal static string BasicErrorMessage {
            get {
                return ResourceManager.GetString("BasicErrorMessage", resourceCulture);
            }
        }
        
        internal static string NoInternetErrorTryAgain {
            get {
                return ResourceManager.GetString("NoInternetErrorTryAgain", resourceCulture);
            }
        }
    }
}
